
- name: Setup Bastion Host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import Bastion setup variables
      include_vars: vars/bastion_setup

    - name: Import Output variables
      include_vars: vars/output_vars
    