

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: Create VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        state: "{{state}}"
      register: vpcout
         
    - name: Create Public Subnet 1 in Zone 1
      ec2_vpc_subnet: 
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        az: "{{zone1}}"
        cidr: "{{subnet_pub1_cidr}}"
        map_public: yes
        resource_tags:
          name: demo-vpc-pubsub1
      register: pubsub1out