

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: Create VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        state: "{{state}}"
      register: vpcout

    # - debug:
    #     var: vpcout
         
    - name: Create Public Subnet 1 in zone 1
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az1}}"
        cidr: "{{subnet_pub1_cidr}}"
        map_public: yes
        resource_tags:
          Name: demo-vpc-pubsub1
      register: pubsub1out


    - name: Create Public Subnet 2 in zone 2
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az2}}"
        cidr: "{{subnet_pub2_cidr}}"
        map_public: yes
        resource_tags:
          Name: demo-vpc-pubsub2
      register: pubsub2out


    - name: Create Public Subnet 3 in zone 3
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az3}}"
        cidr: "{{subnet_pub3_cidr}}"
        map_public: yes
        resource_tags:
          Name: demo-vpc-pubsub3
      register: pubsub3out

    - name: Create Private Subnet 1 in zone 1
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az1}}"
        cidr: "{{subnet_priv1_cidr}}"
        resource_tags:
          Name: demo-vpc-privsub1
      register: privsub1out

    - name: Create Private Subnet 2 in zone 2
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az2}}"
        cidr: "{{subnet_priv2_cidr}}"
        resource_tags:
          Name: demo-vpc-privsub2
      register: privsub2out

    - name: Create Private Subnet 3 in zone 3
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az3}}"
        cidr: "{{subnet_priv3_cidr}}"
        resource_tags:
          Name: demo-vpc-privsub3
      register: privsub3out


      