
- name: Setup VPC
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: Create VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        state: "{{state}}"
      register: vpcout

         
    - name: Create Public Subnet 1 in zone 1
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az1}}"
        cidr: "{{subnet_pub1_cidr}}"
        map_public: yes
        resource_tags:
          Name: demo-vpc-pubsub1
      register: pubsub1out


    - name: Create Public Subnet 2 in zone 2
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az2}}"
        cidr: "{{subnet_pub2_cidr}}"
        map_public: yes
        resource_tags:
          Name: demo-vpc-pubsub2
      register: pubsub2out

    - name: Create Private Subnet 1 in zone 1
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az1}}"
        cidr: "{{subnet_priv1_cidr}}"
        resource_tags:
          Name: demo-vpc-privsub1
      register: privsub1out


    - name: Create Private Subnet 2 in zone 2
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az2}}"
        cidr: "{{subnet_priv2_cidr}}"
        resource_tags:
          Name: demo-vpc-privsub2
      register: privsub2out

    - name: Internet Gateway setup
      ec2_vpc_igw:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        resource_tags:
          Name: demo-vpc-igw
      register: igwout


    - name: Set up route table for public subnet
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        resource_tags:
          Name: demo-vpc-rtb
        subnets:
          - "{{pubsub1out.subnet.id}}"
          - "{{pubsub2out.subnet.id}}"
          
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igwout.gateway_id}}"
      register: rtbpubout

    
    - name: Create Security Group for NAT instance
      ec2_group:
        name: "NATSG"
        description: "This is the security group for the NAT instance"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        rules:
          # - proto: tcp
          #   from_port: 22
          #   to_port: 22
          #   cidr_ip: 0.0.0.0/0
          #   rule_desc: allow ssh connection
          
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all connections
      register: natsgout
  
    - name: Create ec2 key
      ec2_key:
        name: sample-key
        region: "{{region}}"
      
      register: key_out
    
    - name: Save private key into sample-key.pem
      copy: 
        content: "{{key_out.key.private_key}}"
        dest: "./sample-key.pem"
        mode: 0600
      
      when: key_out.changed

    # - name: Set up a NAT instance
    #   ec2:
    #     key_name: "sample-key"
    #     vpc_subnet_id: "{{pubsub1out.subnet.id}}"
    #     image: "{{nat_instance_ami}}"
    #     region: "{{region}}"
    #     source_dest_check: no
    #     exact_count: 1
    #     count_tag:
    #       Name: "Nat Instance"
    #     wait: yes
    #     wait_timeout: 600
    #     instance_type: t2.medium
    #     group_id:
    #       - "{{natsgout.group_id}}"
    #     assign_public_ip: true
    #     instance_tags:
    #       Name: "Nat Instance"
    #   register: natinstanceout

    - name: Setup NAT Gateway
      ec2_vpc_nat_gateway:
        state: "{{state}}"
        subnet_id: "{{pubsub1out.subnet.id}}"
        wait: yes
        region: "{{region}}"
        if_exist_do_not_create: true
      register: natgatewayout
    
    - name: Set up route table for NAT gateway
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        resource_tags:
          Name: demo-vpc-nat-rtb
        subnets:
          - "{{privsub1out.subnet.id}}"
          - "{{privsub2out.subnet.id}}"
        routes:
          - dest: "{{ip}}"
            gateway_id: "{{natgatewayout.nat_gateway_id}}"
      register: rtbnatout


    - name: Save outputs into a file
      copy:
        content: "region: {{region}}\nvpc_id: {{vpcout.vpc.id}}\npubsub1id: {{pubsub1out.subnet.id}}\npubsub2id: {{pubsub2out.subnet.id}}\nprivsub1id: {{privsub1out.subnet.id}}\nprivsub2id: {{privsub2out.subnet.id}}\nigwid: {{igwout.gateway_id}}\nrtbpubid: {{rtbpubout.route_table.id}}\nnatgatewayid: {{natgatewayout.nat_gateway_id}}\nrtbnatid: {{rtbnatout.route_table.id}}"
        dest: vars/output_vars



      