

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: Create VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout
         
    - name: Create Public Subnet
      ec2_vpc_subnet: 
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{az1}}"
        cidr: "{{subnet_pub1_cidr}}"
        map_public: yes
        resource_tags:
          name: demo-vpc-pubsub1
      register: pubsub1out


      