

- name: Setup Nginx
  hosts: webserver
  gather_facts: no
  tasks:
    - name: Install php8.1-fpm
      apt:
        name: php8.1-fpm
        state: present
        update_cache: yes
        
    - name: Install nginx
      apt: 
        name: nginx
        state: present
        update_cache: yes
      tags:
        - package
    
    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
       - svc
    
    - name: Disable default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      tags:
        - conf
    
    - name: Deploy web config
      template:
        src: templates/nginx.j2
        dest: /etc/nginx/sites-available/site
      
      tags:
        - conf

    - name: Deploy web config
      template:
        src: /etc/nginx/sites-available/site
        dest: /etc/nginx/sites-enabled/site
        state: link
      notify:
        - Restart Nginx
      
      tags:
        - conf

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
    
